---
bitbucket_database_host: 1.1.1.2
bitbucket_version: 5.10.1
#bitbucket_version: 7.0.1

bitbucket_database_jdbc_custom_config: []

#backup_restore: 
#  bitbucket:
#    path_pattern: '*'
#    folder: home
#    remove_folder: home/shared/search/data/nodes
#    force: false
#    stop_start_service: bitbucket
