---
jira_version: 7.12.1
# jira_version: 7.13.14
# jira_version:  8.5.5
# jira_manual_upgrade: yes

jira_database_host: 1.1.1.2

#backup_restore: 
#  jira:
#    path_pattern: '*'
#    folder: .
#    force: false
#    stop_start_service: jira

# Example Oracle settings
# jira_database_url: jdbc:oracle:thin:@//1.1.1.111:1521/jira_lab.localdomain
# jira_database_ojdbc_jar_url: https://example.com/ojdbc8.jar
# jira_database_driver_class: oracle.jdbc.OracleDriver
# jira_database_validation_query: select 1 from dual
# jira_database_type: oracle10g
# jira_database_name: jira_lab
# jira_database_username: jira_lab
# jira_database_password: sportsbar
# jira_database_schema: nil

# Atlassian Support recommended JVM arguments and proxy config
jira_jvm_support_recommended_args: >-
  -Datlassian.plugins.enable.wait=300
  -XX:+UnlockExperimentalVMOptions
  -XX:+UseCGroupMemoryLimitForHeap
  -XX:MaxRAMFraction=1
  -Dhttps.proxyHost={{ proxy_host }}
  -Dhttps.proxyPort={{ proxy_port }}
  -Dhttp.nonProxyHosts=*.nip.io\|localhost
# note escape character for nonProxyHosts

jira_libraries: 
  - url: https://github.com/javamelody/jira-confluence-javamelody/releases/download/1.83.0/jira-confluence-javamelody-1.83.0.jar
    checksum: sha256:2007bf47db63690f61a919cc828332d1d852c283c48137e07db608dd3c82e65e
