---
# Name of volume group
lvm_vg: 'data'

# List of devices to use for volume group
lvm_vg_devices: ['/dev/sdx']

# Roles ( external / internal) supported by this lvm role
lvm_roles_supported:
  - nfs
  - postgresql
  - sonarqube
  - myapp

lvm_roles:
  nfs:
    size: '10g' 
    path: '/nfs'
  postgresql:
    size: '10g'
    path: '/var/lib/postgresql'
  sonarqube:
    size: '10g'
    path: '{{ sonar_home if sonar_home is defined else "/opt/sonarqube" }}'
  myapp:
    size: '1g' 
    path: '{{ myapp_home if myapp_home is defined else "/opt/myapp" }}'
