---
- name: Get roles
  set_fact: cacerts_roles_node="{{ cacerts_roles_supported | intersect(ansible_role_names_cleaned) }}"

- name: "Import trusted sites certs for {{ role_item }}"
  include: trusted_sites.yml
  with_items: "{{ cacerts_roles_node }}"
  vars:
    role: "{{ role_item }}"
  loop_control:
    loop_var: role_item # prevent variable collision

- name: "Download {{ item['url'] }} for import"
  get_url:
    url: "{{ item['url'] }}"
    dest: "/tmp/{{ item['url']|basename }}"
  with_items: "{{ cacerts_import_certs_urls }}"

- name: "Import downloaded certs / bundles for {{ role_item }}"
  include: import_urls.yml
  with_items: "{{ cacerts_roles_node }}"
  vars:
    role: "{{ role_item }}"
  loop_control:
    loop_var: role_item
