---
- name: "Import trusted sites SSL cert in keystore for {{ role }}"
  java_cert:
    cert_url: "{{ item['url'] }}"
    cert_port: "{{ item['port'] }}"
    keystore_path: "{{ cacerts_roles[role].keystore_path }}"
    keystore_pass: "{{ cacerts_roles[role].keystore_pass }}"
    executable: "{{ cacerts_roles[role].executable|default(omit) }}"
    state: present
  with_items: "{{ cacerts_trusted_sites }}"
  notify: "{{ cacerts_roles[role].notify|default(omit) }}"
