---
sonarqube_version: 6.7
#sonarqube_version: 7.9.1

sonarqube_versions:
  6.7:
    plugins:
      build_breaker:
        pattern: 'sonar-build-breaker-plugin-*.jar'
        url: "https://github.com/jbocc/sonar-build-breaker/releases/download/2.2/sonar-build-breaker-plugin-2.2.jar"
        checksum: "22f51c0f02d6d5ff6d7bc9c91150e9576bee72067de1d903270e4eb96f4f6fc2"
  7.9.1:
    plugins:
      build_breaker:
        pattern: 'sonar-build-breaker-plugin-*.jar'
        url: "https://github.com/adnovum/sonar-build-breaker/releases/download/v2.3/sonar-build-breaker-plugin-2.3.jar"
        checksum: "fa7a922e3693813ca12c09b283da02fa57cfe963ab7f0e1e266ab4ddc6ba0307"

sonarqube_plugins:
  json:
    pattern: 'sonar-json-plugin-*.jar'
    url: "https://github.com/racodond/sonar-json-plugin/releases/download/2.1/sonar-json-plugin-2.1.jar"
    checksum: "07fce6ffc032c9740900822af81bf7a8d9d38de1f0a3cb10e53e3b2a20126979"
  widgetlab:
    pattern: 'sonar-widget-lab-plugin-*.jar'
    url: "https://github.com/SonarQubeCommunity/sonar-widget-lab/releases/download/1.8.1/sonar-widget-lab-plugin-1.8.1.jar"
    checksum: "2efb300427a0c5439d91234ce831137b28819da2007354482613cd391b979ff9"

manala_motd_message:  "SonarQube {{ sonarqube_version }} Server"

c2_alias:
  roles:
    sonarqube:
      logs: ["{{ sonarqube_home }}/sonarqube/logs/*.log"]
      configs: 
        - "{{ sonarqube_home }}/sonarqube/conf/sonar.properties"
        - "/etc/systemd/system/sonarqube.service" 

https_proxy_roles:
  sonarqube:
    hostname: sonarqube.tech
    proxy_port: 443
    port: "{{ sonarqube_web_port }}"
    context: "{{ sonarqube_web_context }}"

adoptopenjdk:
  version: "jdk11_0411_oj9"

sonarqube_java_bin: 
  Debian: '{{ adoptopenjdk_java_home }}/bin/java'
  RedHat: '{{ adoptopenjdk_java_home }}/bin/java'

sonarqube_proxy:
  host: '{{ proxy_host }}'
  port: '{{ proxy_port }}'  

apache_remove_default_vhost: true