---
ds_version: 6.5.3
home: /opt/ds

ds_owner: forgerock
ds_group: forgerock

ds_packages: []

ds_versions:
  6.5.3:
    url: https://github.com/....
    checksum: "sha256: 7dff615fc2add75f65bcf27ef09d8cf585e0f38c63c0781d90c79d537647d380"

ds_versions_sequence: [6.5.3]
