---
opends_version: 6.5.4
opends_home: /opt/ds

ds_owner: forgerock
ds_group: forgerock

ds_packages: []

ds_versions:
  6.5.4:
    url: file:///vagrant/DS-6.5.4.zip
    checksum: "sha256: 820a197f4ac11b020c653ef00c684e63034df1f9f591b826ee4735c4bde7b8f1"

opends_versions_sequence: [6.5.4]
