---
opends_version: 6.5.4
opends_home: /opt/ds

ds_owner: forgerock
ds_group: forgerock

ds_packages: []

ds_versions:
  6.5.4:
    url: file:///vagrant/DS-6.5.4.zip
    checksum: "sha256: 820a197f4ac11b020c653ef00c684e63034df1f9f591b826ee4735c4bde7b8f1"

opends_versions_sequence: [6.5.4]
opends_hostname: fr1.example.com 
# Probably overwritten in the group_vars for a specific play, eg. with a nip.io adress

opends_install_config: >
  ./setup directory-server 
  --rootUserDN "cn=Directory Manager" 
  --rootUserPassword FRdemo123  
  --monitorUserPassword FRdemo123 
  --hostname {{ opends_hostname }} 
  --ldapPort 3389 
  --ldapsPort 3636 
  --adminConnectorPort 34444 
  --profile am-config 
  --set am-config/amConfigAdminPassword:FRdemo123 
  --acceptLicense
  
  
# --productionMode 
# --httpPort 38081 
# --httpsPort 38443 
