---
- name: Unzip
  unarchive:
    dest: "{{ opends_home_link }}"
    owner: "{{ opends_owner }}"
    group: "{{ opends_group }}"
    remote_src: yes
    src: "{{ opends_home_link }}/downloads/{{ opends_versions[opends_version]['url']|basename }}"

# Check setup performed
- name: Stat config dir
  stat:
    path: "{{ opends_home_link }}/opendj/config/"
  register: config_dir

#- name: Status
#  command: 
#    cmd: "{{ opends_home_link }}/opendj/bin/status --offline"
#  register: opends_status
#  ignore_errors: yes
