---
- name: Unzip
  unarchive:
    dest: "{{ opends_home }}/{{ opends_version }}/config"
    owner: "{{ ds_owner }}"
    group: "{{ ds_group }}"
    remote_src: yes
    src: "{{ opends_home }}/downloads/{{ ds_versions[opends_version]['url']|basename }}"

# Check setup performed
- name: Stat config dir
  stat:
    path: "{{ opends_home }}/{{ opends_version }}/config"
  register: config_dir

#opends_setup_config:
#  rootUserDN: "cn=Directory Manager"
#  rootUserPassword: FRdemo123
#  monitorUserPassword: FRdemo123
#  hostname: {{ opends_hostname }}
#  ldapPort: 3389
#  ldapsPort: 3636
#  adminConnectorPort: 34444
#  profile: am-config
#  set: am-config/amConfigAdminPassword:FRdemo123
#  acceptLicense:

# ./setup directory-server 

- debug:
    msg: "Command: {{ opends_setup_config|opends_cmd }}"

- name: Setup OpenDS
  command:
    cmd: "./setup directory-server {{ opends_setup_config|opends_cmd }}"
  register: ds_setup_status

# Check dat ie ook in opendj/user komt!
#- name: Status
#  command: 
#    cmd: "{{ ds_home}}/opendj/bin/status --offline"
#  register: ds_status
#  ignore_errors: yes
