---
- name: Unzip
  unarchive:
    dest: "{{ ds_home_link }}"
    owner: "{{ ds_owner }}"
    group: "{{ ds_group }}"
    remote_src: yes
    src: "{{ ds_home_link }}/downloads/{{ ds_versions[ds_version]['url']|basename }}"

# Check setup performed
- name: Stat config dir
  stat:
    path: "{{ ds_home_link }}/opendj/config/"
  register: config_dir

# Check dat ie ook in opendj/user komt!
#- name: Status
#  command: 
#    cmd: "{{ ds_home_link }}/opendj/bin/status --offline"
#  register: ds_status
#  ignore_errors: yes
