---
# nexus_version: 3.7.1-02
nexus_version: 3.19.1-01
nexus_public_hostname: sh.1.1.1.3.nip.io
nexus_public_scheme: https
vault_nexus_admin_password: supersecret

nexus_default_context_path: /nexus

nexus_api_hostname: sh.1.1.1.3.nip.io
nexus_api_scheme: https
nexus_api_validate_certs: false
nexus_api_context_path: /nexus/
nexus_api_port: 443

#backup_restore: 
#  nexus:
#    path_pattern: '*'
#    folder: data
#    force: false
#    stop_start_service: nexus

