---
- name: bitbucket.properties
  template:
    dest: "{{ bitbucket_home_version_home }}/shared/bitbucket.properties"
    owner: "{{ bitbucket_owner }}"
    group: "{{ bitbucket_group }}"
    src: bitbucket.properties.j2
  notify: bitbucket-systemctl-restart

- name: env file BITBUCKET_HOME etc
  template:
   dest: /etc/profile.d/bitbucket.sh
   src: bitbucket.sh.j2
