---
- name: Create a directory for openam if it does not exist
  file:
    path: /opt/openam
    state: directory
    mode: '0755'

- name: Download openam from internet (zip contains openam folder hence unpack will create that)
  unarchive:
    src: https://github.com/OpenIdentityPlatform/OpenAM/releases/download/14.4.2/OpenAM-14.4.2.zip
    dest: /opt/
    remote_src: yes

- name: Copy openam file with owner and permissions
  copy:
    src: /opt/openam/OpenAM-14.4.2.war
    dest: /opt/tomcat/webapps/openam.war
    owner: root
    group: root
    mode: a+x
    remote_src: yes

- name: Restart service httpd, in all cases
  service:
    name: tomcat
    state: restarted
