---
- name: Install packages for apache tomcat
  yum:
    name: "{{ item }}"
    state: present  
  with_items:
    - tomcat
    - tomcat-webapps
    - tomcat-admin-webapps
    - tomcat-docs-webapp 
    - tomcat-javadoc

- name: Enable service tomcat.service, and not touch the state
  service:
    name: tomcat
    enabled: yes

- name: Start service tomcat.service, if not started
  service:
    name: tomcat
    state: started