---
- name: Add system message
  jenkins_script:
    url: "{{ jenkins_url }}"
    validate_certs: no
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"
    script:  "{{ lookup('file', 'scripts/set_system_message.groovy') }}"
    args:
      system_message: "{{ jenkins_system_message }}"
  register: script_result
  changed_when: "'changed' in script_result.output"

- name: JDK auto-installers init script
  template:
    dest: "/var/lib/jenkins/init.groovy.d/auto_installer_jdk.groovy"
    owner: "jenkins"
    group: "jenkins"
    src: "auto_installer_jdk.groovy.j2"
  notify: restart jenkins
