---
proxy_allowed_ips:
  - 1.1.1.1
  - 1.1.1.2
  - 1.1.1.3
  - 1.1.1.4
  - 1.1.1.7
  - 1.1.1.8
  - 1.1.1.9
  - 1.1.1.10
proxy_upstream_always_direct_ips:
  - 1.1.1.1 

# dynamic vars set in a role cannot be used on other roles 
# so we set squid_config_directory, squid_config_file here
squid_config_directory: /etc/squid 
squid_config_file: squid.conf
squid_conf_include_dir: /etc/squid/conf.d

# Configure upstream proxy server
# proxy_upstream_server: 10.0.2.2
# proxy_upstream_port: 8888

#squid_cache_rules:
#  - acl: localnet
#    decision: deny

