---
proxy_allowed_ips: 
  - 1.1.1.2
  - 1.1.1.3
  - 1.1.1.4

squid_acls:
  - name: localnet
    classifier: src
    value: "\"{{ proxy_allowd_ips_file }}\""

#squid_cache_rules:
#  - acl: localnet
#    decision: deny

# move to alias
c2_alias:
  roles:
    proxy:
      logs: ["/var/log/squid/*.log","/var/log/squid/squid.out"]
      configs: 
        - "{{ squid_config_directory }}/{{ squid_config_file }}"
        - "{{ proxy_allowd_ips_file }}"
