---
proxy_port: 0
proxy_host: ''
#proxy_no_proxy: 'nip.io' # comma separated list

proxy_allowed_ips: 
  - 1.1.1.2
  - 1.1.1.3
  - 1.1.1.4
  - 1.1.1.7  

squid_acls:
  - name: localnet
    classifier: src
    value: "\"{{ proxy_allowd_ips_file }}\""

reverse_proxy_vhosts:
  sh:
    server_name: sh.1.1.1.3.nip.io 
    port: 443
    proxy_verify: false
    proxy_passes:
      sq:
        proxy_pass: /sonarqube https://1.1.1.4/sonarqube
        #proxy_pass_reverse: /sonarqube https://1.1.1.4/sonarqube/
      nexus:
        proxy_pass: /nexus http://1.1.1.7:8081/nexus nocanon
        proxy_pass_reverse: /nexus http://1.1.1.7:8081/nexus
#squid_cache_rules:
#  - acl: localnet
#    decision: deny

# move to alias
c2_alias:
  roles:
    proxy:
      logs: ["/var/log/squid/*.log","/var/log/squid/squid.out"]
      configs: 
        - "{{ squid_config_directory }}/{{ squid_config_file }}"
        - "{{ proxy_allowd_ips_file }}"
