---
backup_mount: /backup
backup_logs: /backup/logs
backup_tmp: /backup/tmp
backup_split_into_chunks_of: 1000000
backup_alias_prefix: tpelcm
backup_cron_jobs: true

backup_roles_supported: ['sonarqube']

backup_roles:
  sonarqube:
    stop_start_service: sonarqube
    keep: { daily: 3, weekly: 2, monthly: 0, manual: 1 }
    # snapshot: true
    # schedules: ['daily', 'weekly', 'monthly', 'manual']

backup:
  schedules_default: ['daily', 'weekly', 'monthly', 'manual']
  schedules:
    daily: 50 2 * * 1,2,3,4,5
    weekly: 50 2 * * 6
    monthly: 50 2 1 * *

## Crontab for backup_monthly managed by Chef. Changes will be overwritten.

#50 2 1 * * root /etc/backup/scripts/backup_monthly.sh

backup_notify_mail:
  enabled: false
  from: backup@mydomain.com
  to: admin@mydomain.com
  address: mail.local
  port: 25
  domain: mydomain.local
  on_success: true
  on_warning: true
  on_failure: true

backup_notify_slack:
  enabled: false 
  webhook: https://hooks.slack.com/services/...
  channel: infra
  on_success: true
  on_warning: true
  on_failure: true
