---
backup_mount: /backup
backup_logs: /backup/logs
backup_tmp: /backup/tmp
backup_archives: /backup/archives
backup_split_into_chunks_of: 1000000
backup_alias_prefix: tpelcm
backup_cron_jobs: true
backup_restore_db: false
backup_restore_home: false

backup_roles_supported: ['sonarqube', 'myapp']

backup_roles:
  sonarqube:
    stop_start_service: sonarqube
    keep: { daily: 3, weekly: 2, monthly: 0, manual: 1 }
  myapp:
    # stop_start_service: myapp
    keep: { daily: 1, weekly: 0, monthly: 0, manual: 1 }
    # snapshot: true
    # schedules: ['daily', 'weekly', 'monthly', 'manual']

backup:
  schedules_default: ['daily', 'weekly', 'monthly', 'manual']
  schedules:
    daily: 50 2 * * 1,2,3,4,5
    weekly: 50 2 * * 6
    monthly: 50 2 1 * *

backup_restored: []

backup_notify_mail:
  enabled: false
  from: backup@mydomain.com
  to: admin@mydomain.com
  address: mail.local
  port: 25
  domain: mydomain.local
  on_success: true
  on_warning: true
  on_failure: true

backup_notify_slack:
  enabled: false 
  webhook: https://hooks.slack.com/services/...
  channel: infra
  on_success: true
  on_warning: true
  on_failure: true

#backup_restore:
#   sonarqube: 
#     folder: 2019.10.03.05.21.29
#     folder: '*'
#     path: 
#     force: true

