---
backup_mount: '/backup'
backup_logs: '/backup/logs'
backup_tmp: '/backup/tmp'
backup_split_into_chunks_of: 1000000

backup_roles_supported: ['sonarqube']

backup_roles:
  sonarqube:
    stop_start_service: sonarqube
    # snapshot: true
    # schedules: ['daily', 'weekly', 'monthly', 'manual']

backup:
  schedules_default: ['daily', 'weekly', 'monthly', 'manual']
  schedules:
    daily:
    weekly:
    monthly:
    manual:

backup_notify_mail:
  enabled: false
  from: 'backup@mydomain.com'
  to: 'admin@mydomain.com'
  address: 'mail.local'
  port: 25
  domain: 'mydomain.local'
  on_success: true
  on_warning: true
  on_failure: true
