---
backup_utility:
  ubuntu:
    v18:
      url: https://github.com/tpelcm/omnibus-backup/releases/download/v5.0.0.beta2-1-ubuntu1804/backup_5.0.0.beta.2-1_amd64.deb
      checksum: 2363ac2e8d5f38bafd2401d4fec84c9eef548f612f30a76cb82a2fe2d4dc0ec8
  rhel:
    v7:
      url: https://github.com/tpelcm/omnibus-backup/releases/download/v5.0.0.beta2-1-el7/backup-5.0.0.beta.2-1.el7.x86_64.rpm
      checksum: ce4170985fbce068a9b16d08e916ac570af0a82dcdb9c2286753f800bbb90d77
  centos:
    v7:
      url: https://github.com/tpelcm/omnibus-backup/releases/download/v5.0.0.beta2-1-el7/backup-5.0.0.beta.2-1.el7.x86_64.rpm
      checksum: ce4170985fbce068a9b16d08e916ac570af0a82dcdb9c2286753f800bbb90d77
