---
common_packages: []

common_role_packages:
  nexus: ['rsync']

common_ansible_user: tpetools
common_ansible_user_password: supersecure
common_ansible_user_create: false

# common_ansible_authorized_keys: https://raw.githubusercontent.com/hashicorp/vagrant/master/keys/vagrant.pub