---
c2_alias_prefix: tpelcm
c2_alias_editor: nano

c2_alias:
  roles:
    proxy:
      logs: ["/var/log/squid/*.log","/var/log/squid/squid.out"]
      configs: 
        - "{{ squid_config_directory | default(omit) }}/{{ squid_config_file | default(omit) }}"
        - "{{ proxy_allowd_ips_file | default(omit) }}"
    opendj:
      logs: 
        - /opt/opendj/logs/server.out
        - /opt/opendj/logs/errors
        - /opt/opendj/logs/access
      configs: 
        - /etc/rc.d/init.d/opendj



