---
common_packages: ['nfs-common', 'nano']
common_packages: 
  Debian: ['nfs-common', 'nano', 'libffi-dev'] 
  RedHat: ['nfs-utils', 'nano', 'libffi-devel']

nfs_server: nfs
nfs_mounts:
  - { path: /backup, src: '{{ nfs_server }}:/nfs/backup', opts: rw, fstype: nfs, state: mounted }
  