---
- name: Generate server private key
  openssl_privatekey:
    path: "/opt/confluence/confluence/home/https.key"


- openssl_csr:
    path: "/opt/confluence/confluence/home/https.csr"
    privatekey_path: "/opt/confluence/confluence/home/https.key"
    country_name: "NL"
    organization_name: ""
    email_address: ""
    common_name: "tomcat"

- name: Generate a Self Signed OpenSSL certificate.
  openssl_certificate:
    path: /opt/confluence/confluence/home/https.crt
    privatekey_path: /opt/confluence/confluence/home/https.key
    csr_path: /opt/confluence/confluence/home/https.csr
    provider: selfsigned

- name: Import SSL certificate to a keystore, create it if it doesn't exist
  java_cert:
    cert_path: "/opt/confluence/confluence/home/https.crt"
    keystore_path: "/opt/confluence/confluence/home/.keystore"
    keystore_pass: changeit
    keystore_create: yes
    cert_alias: tomcat
    executable: /opt/confluence/confluence/app/jre/bin/keytool






#keystoreFile="<MY_CERTIFICATE_LOCATION>"

