---
- name: Generate server private key
  openssl_privatekey:
    path: "/opt/confluence/https.key"

- openssl_csr:
    path: "/opt/confluence/https.csr"
    privatekey_path: "/opt/confluence/https.key"
    country_name: "NL"
    organization_name: "TPE"
    email_address: "tpe@politie.nl"
    common_name: "confluence.ontwikkel.local"

- name: Generate server certificate.
  openssl_certificate:
    path: "/opt/confluence/https.cert"
    csr_path: "/opt/confluence/https.csr"
    provider: selfsigned
    #vars:
    #  ansible_python_interpreter: /usr/bin/python3

- name: Create a key store for the given certificate (lookup)
  java_keystore:
    name: https
    certificate: "{{lookup('file', '/opt/confluence/https.cert') }}"
    private_key: "{{lookup('file', '/opt/confleunce/https.key') }}"
    password: changeit
    dest: /opt/confluence/keystore.jks



#keystoreFile="<MY_CERTIFICATE_LOCATION>"

