---
- name: confluence-init.properties
  template:
    dest: "{{ confluence_home_version_app }}/confluence/WEB-INF/classes/confluence-init.properties"
    owner: "{{ confluence_owner }}"
    group: "{{ confluence_group }}"
    src: confluence-init.properties.j2
  notify: confluence-systemctl-restart

- name: Check confluence.properties exists
  stat:
    path: "{{ confluence_home_version_home }}/shared/confluence.properties"
  register: confluence_properties_stat


#        when: not stat_result.stat.exists
#
#
#
#- name: confluence.properties
#  template:
#    dest: "{{ confluence_home_version_home }}/shared/confluence.properties"
#    owner: "{{ confluence_owner }}"
#    group: "{{ confluence_group }}"
#    src: confluence.properties.j2
#  notify: confluence-systemctl-restart
#
#- name: env file CONFLUENCE_HOME etc
#  copy:
#    content: >
#      export CONFLUENCE_HOME={{ confluence_home_version_home }}
#      export CONFLUENCE_USER={{ confluence_owner }}
#    dest: /etc/profile.d/confluence.sh
#    owner: "{{ confluence_owner }}"
#    group: "{{ confluence_group }}"
