---
- name: Configure
  template:
    src: sonar.properties.j2
    dest: "{{ sonarqube_home }}/{{ sonarqube_version_directory }}/conf/sonar.properties"
    mode: 0755
    backup: yes
  notify: restart sonarqube
