---
- name: Add linux user
  user:
    name: sonarqube
    comment: SonarQube
    shell: /bin/bash

- name: Create root directory
  file:
    path: "{{ sonarqube_home }}"
    state: directory
    group: sonarqube
    owner: sonarqube 

- name: Create install folder
  file:
    path: "{{sonarqube_home}}/{{ sonarqube_version_directory }}"
    state: directory
    group: sonarqube
    owner: sonarqube    
  register: install_symlink

- name: Check installed
  stat: 
    path: "{{ sonarqube_home }}/{{ sonarqube_version_directory }}/conf"
  register: sonarqube_installed

- name: Download
  get_url:
    url: "{{ sonarqube_download_url }}"
    dest: "/tmp/{{ sonarqube_version_directory }}.zip"
    validate_certs: "{{ sonarqube_download_validate_certs }}"
  notify: restart sonarqube
  when: sonarqube_installed.stat.exists == false

- name: Unzip package
  package:
    name: unzip
    state: present

- name: Unzip
  unarchive:
    src: "/tmp/{{ sonarqube_version_directory }}.zip"
    dest: "{{ sonarqube_home }}"
    copy: false
    group: sonarqube
    owner: sonarqube    
  when: sonarqube_installed.stat.exists == false

- name: Create symbolic link install
  file:
   src: "{{ sonarqube_home }}/{{ sonarqube_version_directory }}"
   dest: "{{ sonarqube_home }}/sonarqube"
   state: link

- name: Create symbolic link jar 
  file:
   src: "{{ sonarqube_home }}/{{ sonarqube_version_directory }}/lib/sonar-application-{{ sonarqube_version }}.jar"
   dest: "{{ sonarqube_home }}/{{ sonarqube_version_directory }}/lib/sonar-application.jar"
   state: link
