---
- name: Add linux user
  user:
    name: sonarqube
    comment: SonarQube
    shell: /bin/bash

- name: Create root directory
  file:
    path: "{{ sonarqube_home }}"
    state: directory
    group: sonarqube
    owner: sonarqube 

- name: Create install folder
  file:
    path: "{{sonarqube_home_version }}"
    state: directory
    group: sonarqube
    owner: sonarqube    
  register: install_symlink

- name: Check installed
  stat: 
    path: "{{ sonarqube_home_version }}/conf"
  register: sonarqube_installed

- name: Download
  get_url:
    url: "{{ sonarqube_versions[sonarqube_version]['url'] }}"
    dest: "/tmp/{{ sonarqube_home_version|basename }}.zip"
    validate_certs: "{{ sonarqube_download_validate_certs }}"
    checksum: "{{ sonarqube_versions[sonarqube_version]['checksum'] }}"
  notify: restart sonarqube
  when: sonarqube_installed.stat.exists == false

- name: Unzip package
  package:
    name: unzip
    state: present

- name: Unzip
  unarchive:
    src: "/tmp/{{ sonarqube_home_version|basename }}.zip"
    dest: "{{ sonarqube_home }}"
    copy: false
    group: sonarqube
    owner: sonarqube    
  when: sonarqube_installed.stat.exists == false

- name: Create symbolic link install
  file:
   src: "{{ sonarqube_home_version }}"
   dest: "{{ sonarqube_home }}/sonarqube"
   state: link

- name: Create symbolic link jar 
  file:
   src: "{{ sonarqube_home_version }}/lib/sonar-application-{{ sonarqube_version }}.jar"
   dest: "{{ sonarqube_home_version }}/lib/sonar-application.jar"
   state: link

- name: Copy data dir ( part of upgrade )
  command: "rsync -az --delete --recursive {{ sonarqube_home_version_current }}/extensions/plugins/ {{ sonarqube_home_version }}/extensions/plugins/"
  when: sonarqube_lcm['operation'] == 'upgrade' 

- name: Raise mmap counts limit ( set at boot )
  copy:
    dest: /usr/lib/sysctl.d/100-sonarqube.conf
    content: 'vm.max_map_count={{ sonarqube_max_map_count }}'
  register: vm_max_map_count

- name: Raise mmap counts limit
  command: 'sysctl -w vm.max_map_count={{ sonarqube_max_map_count }}'
  when: vm_max_map_count|changed 
