---
- name: Stop SonarQube for LCM
  service: name=sonarqube state=stopped
  when: sonarqube_lcm['operation'] in ['upgrade','rollback','rollforward'] 

- include: database.yml
- include: install.yml
- include: configuration.yml
- include: plugins.yml
- include: service.yml
