---
- name: remove other version of plugins
  remove_old_plugin_version:
    plugin_dir: "{{sonarqube_home_version }}/extensions/plugins"
    pattern: "{{ sonarqube_plugins[item]['pattern'] }}"
    url: "{{ sonarqube_plugins[item]['url'] }}"
  with_items: "{{ sonarqube_plugins }}"

- name: community plugins
  get_url:
    url: "{{ sonarqube_plugins[item].url }}"
    checksum: "sha256:{{ sonarqube_plugins[item].checksum }}"
    dest: "{{sonarqube_home_version }}/extensions/plugins"
    group: sonarqube
    owner: sonarqube
  notify: restart sonarqube   
  with_items: "{{ sonarqube_plugins }}"
  when: sonarqube_plugins is defined

