---
- name: awx.yml
  hosts: awx
  become: yes

  roles:
    - { role: common,                       tags: ["common"] }
    - { role: geerlingguy.docker,           tags: ["awx", "docker"] }
    - { role: geerlingguy.awx,              tags: ["awx"] }

#  vars:
#    nodejs_version: "6.x"
#    # nodejs_version: "12.16.3" # LTS
#   pip_install_packages:
#      - name: docker-py
