---
- name: awx.yml
  hosts: awx
  become: yes

  roles:
    - { role: common,                       tags: ["common"] }
    - { role: geerlingguy.docker,           tags: ["awx", "docker"] }
    - { role: awx,                          tags: ["awx"] }
