---
- name: awx.yml
  hosts: awx
  become: yes

  roles:
    - { role: common,                       tags: ["common"] }
    - { role: geerlingguy.docker,           tags: ["awx", "docker"] }
    - { role: awx,                          tags: ["awx"] }
    - { role: backup,                       tags: ["backup"] }

  vars:
    common_pip_packages_extra: ['docker','docker-compose']
