---
- name: bitbucket.yml
  hosts: bitbucket
  become: yes

  roles:
    - { role: c2.core.common,               tags: ["common"] }
    - { role: c2.core.postgresql_client,    tags: ["database"], when: bitbucket_database_type == 'postgresql' }
    - { role: c2.core.oracle_client,        tags: ["database"], when: bitbucket_database_type == 'oracle' }
    - { role: c2.forgerock222.test,            tags: ["test"] }
    - { role: geerlingguy.git,              tags: ["bitbucket"] }
    - { role: bitbucket,                    tags: ["bitbucket"] }
    - { role: backup,                       tags: ["backup"] }

  vars:
    git_install_from_source: true
    git_version: "2.16.2"
    git_install_from_source_force_update: true
    adoptopenjdk:
      version: false # use embedded java
