---
- name: bitbucket.yml
  hosts: bitbucket
  become: yes

  roles:
    - { role: common,                       tags: ["common"] }
    - { role: postgresql_client,            tags: ["database"], when: bitbucket_database_type == 'postgresql' }
    - { role: oracle_client,                tags: ["database"], when: bitbucket_database_type == 'oracle' }
    - { role: geerlingguy.git,              tags: ["bitbucket"] }
    - { role: bitbucket,                    tags: ["bitbucket"] }
    - { role: backup,                       tags: ["backup"] }

  vars:
    git_install_from_source: true
    git_version: "2.16.2"
    git_install_from_source_force_update: true
    adoptopenjdk:
      version: false # use embedded java
