---
- name: confluence.yml
  hosts: confluence
  become: yes

  roles:
    - { role: common,                       tags: ["common"] }
    - { role: postgresql-client,            tags: ["confluence", "postgresql"] }    
    - { role: confluence,                   tags: ["confluence"] }
    - { role: backup,                       tags: ["common", "backup"] }
