---
- name: jira.yml
  hosts: jira
  become: yes

  roles:
    - { role: common,                       tags: ["common"] }
    - { role: postgresql-client,            tags: ["jira", "postgresql"] }    
    - { role: jira,                         tags: ["jira"] }
    - { role: backup,                       tags: ["common", "backup"] }
