---
- name: jira.yml
  hosts: jira
  become: yes

  roles:
    - { role: common,                       tags: ["common"] }
    - { role: postgresql-client,            tags: ["jira", "postgresql"] }    
    - { role: java,                         tags: ["java"] }
    - { role: jira,                         tags: ["jira"] }
    - { role: backup,                       tags: ["common", "backup"] }

 #vars:
 #   git_install_from_source: true
 #   git_version: "2.16.2"
 #   git_install_from_source_force_update: true
