---
- name: postgresql.yml | All roles
  hosts: postgresql
  become: yes

  roles:
    - { role: c2.core.common,             tags: ["common"] }
    - { role: galaxyproject.postgresql,   tags: ["postgresql"] }
    - { role: postgresql,                 tags: ["postgresql"] }
