---
- name: proxy.yml | All roles
  hosts: proxy
  become: yes

  roles:
    - { role: common,             tags: ["common"] }
    - { role: tpelcm.squid,       tags: ["proxy"] }
    - { role: proxy,              tags: ["proxy"] }
