---
- name: Sites
  hosts: sites
  become: yes

  roles:
    - { role: common,                       tags: ["common"] }
    - { role: backup,                       tags: ["backup"] }
    - { role: sites,                        tags: ["sites"] }
