---
jira_home: /opt/jira

jira_version: 7.12.1

jira_jvm_minimum_memory: 512m
jira_jvm_maximum_memory: 1g

jira_web_port: 8080
jira_web_context: /jira
jira_rmi_port: 8005

jira_owner: jira
jira_group: jira

jira_manual_upgrade: no

jira_database_username: jira
jira_database_password: supersecure

jira_database_host: localhost
jira_database_port: 5432
jira_database_name: jira
jira_database_admin_username: ansible
jira_database_admin_password: supersecure
jira_database_template: template0
jira_database_type: postgres72
jira_database_driver_class: org.postgresql.Driver
jira_database_validation_query: select 1
jira_database_schema: public
jira_datababse_setbigstringtryclob: no # yes for oracle
jira_database_custom: no # yes for oracle
jira_database_lc_collate: C
jira_database_lc_ctype: C
# Oracle example settings
# jira_database_custom: yes
# jira_database_url: jdbc:oracle:thin:@//1.1.1.111:1521/jira_lab.localdomain
# jira_database_url: jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=1.1.1.111)(PORT=1521))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=jira.localdomain)))
# jira_database_ojdbc_jar_url: https://example.com/ojdbc8.jar
# jira_database_driver_class: oracle.jdbc.OracleDriver
# jira_database_validation_query: select 1 from dual
# jira_database_type: oracle10g
# jira_database_schema: nil
# jira_datababse_setbigstringtryclob: yes


# Proxy and context path setup.
jira_proxy_name: sh.1.1.1.3.nip.io
jira_proxy_port: 443

jira_versions:
  7.12.1:
    url: https://product-downloads.atlassian.com/software/jira/downloads/atlassian-jira-software-7.12.1-x64.bin
    checksum: sha256:c01a978294137088f699cfde764ad89e9b48df3c0ce6b9c1503fe7eeb0be9310
  8.5.4:
    url: https://product-downloads.atlassian.com/software/jira/downloads/atlassian-jira-software-8.5.4-x64.bin
    checksum: sha256:6782e94b30d480801e5a933c869a0d9be4055ed393d88b1a975c1b7ec7e06721
  8.5.5:
    url: https://product-downloads.atlassian.com/software/jira/downloads/atlassian-jira-software-8.5.5-x64.bin
    checksum: sha256:07a95b111703c6a316a29b993387aff7dcf3d86de1251d06030ddce4eb10c62a

jira_versions_sequence: ['7.12.1','8.5.5']

# Atlassian Support recommended JVM arguments.
jira_jvm_support_recommended_args: >-
  -Datlassian.plugins.enable.wait=300
  -XX:+UnlockExperimentalVMOptions
  -XX:+UseCGroupMemoryLimitForHeap
  -XX:MaxRAMFraction=1

#-Djavax.net.ssl.trustStore=/path#
#-Djavax.net.ssl.trustStore
#-Dhttp.proxyHost#
#-Dhttp.proxyPort
#-Dhttps.proxyHost
#-Dhttps.proxyPort

# Session timeout.
#jira_session_timeout: "300"

jira_jmx:
  enable: no
#  remote_port: 3333
#  rmi_port: 3333
#  rmi_server_hostname: sh.1.1.1.11.nip.io
#  password: supersecret

jira_libraries: []
#  - url: https://github.com/javamelody/jira-confluence-javamelody/releases/download/1.83.0/jira-confluence-javamelody-1.83.0.jar
#    checksum: 2007bf47db63690f61a919cc828332d1d852c283c48137e07db608dd3c82e65e

# https://confluence.atlassian.com/x/PRCEOQ
jira_packages:
  RedHat: ['fontconfig']
  CentOS: ['dejavu-sans-fonts','fontconfig']