---
jira_home: /opt/jira

jira_version: 7.12.1

jira_jvm_minimum_memory: 512m
jira_jvm_maximum_memory: 1g

jira_web_port: 8080
jira_web_context: /jira
jira_rmi_port: 8005

jira_owner: jira
jira_group: jira

jira_database_username: jira
jira_database_password: supersecure

jira_database_host: localhost
jira_database_port: 5432
jira_database_name: jira
jira_database_admin_username: ansible
jira_database_admin_password: supersecure
jira_database_template: template0

#jira_database_jdbc_custom_config:
#  - jdbc.driver=org.postgresql.Driver
#  - jdbc...

# Proxy and context path setup.
jira_proxy_name: sh.1.1.1.3.nip.io
jira_proxy_port: 443

jira_versions:
  7.12.1:
    url: https://product-downloads.atlassian.com/software/jira/downloads/atlassian-jira-software-7.12.1-x64.bin
    checksum: sha256:c01a978294137088f699cfde764ad89e9b48df3c0ce6b9c1503fe7eeb0be9310
  8.5.4:
    url: https://product-downloads.atlassian.com/software/jira/downloads/atlassian-jira-software-8.5.4-x64.bin
    checksum: sha256:6782e94b30d480801e5a933c869a0d9be4055ed393d88b1a975c1b7ec7e06721

jira_versions_sequence: ['7.12.1','8.5.4']

# Atlassian Support recommended JVM arguments.
jira_jvm_support_recommended_args: >-
  -Datlassian.plugins.enable.wait=300
  -XX:+UnlockExperimentalVMOptions
  -XX:+UseCGroupMemoryLimitForHeap
  -XX:MaxRAMFraction=1

#-Djavax.net.ssl.trustStore=/path#
#-Djavax.net.ssl.trustStore
#-Dhttp.proxyHost#
#-Dhttp.proxyPort
#-Dhttps.proxyHost
#-Dhttps.proxyPort

# Session timeout.
#jira_session_timeout: "300"

#jira_jmx:
#  enable: yes
#  remote_port: 3333
#  rmi_port: 3333
#  rmi_server_hostname: sh.1.1.1.11.nip.io
#  password: supersecret
