---
sonarqube_home: /opt/sonarqube
sonarqube_download_validate_certs: true

sonarqube_version: 6.7
sonarqube_download_url: "https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-{{ sonarqube_version }}.zip"

sonarqube_java_bin: 
  Debian: /usr/lib/jvm/java-11-openjdk-amd64/bin/java
  RedHat: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.222.b10-0.el7_6.x86_64/jre/bin/java
  
sonarqube_xms: 32m # 128m
sonarqube_xmx: 32m # 2048m

sonarqube_web_port: 9000
sonarqube_web_context: '/sonarqube'

sonarqube_database_username: sonarqube
sonarqube_database_password: supersecure

sonarqube_database_host: localhost
sonarqube_database_port: "5432"
sonarqube_database_name: sonarqube
sonarqube_database_admin_username: ansible
sonarqube_database_admin_password: supersecure

sonarqube_python_library: python-psycopg2

sonarqube_plugins: []

#sonarqube_proxy:
#  host: localhost
#  port: 3128

# Facts set by lcm role - only
# sonarqube_database_name_version: sonarqube_6_7
# sonarqube_home_version: /opt/sonarqube/sonarqube_6_7
