---
confluence_home: /opt/confluence

confluence_version: 5.10.1

confluence_jvm_minimum_memory: 512m
confluence_jvm_maximum_memory: 1g

confluence_web_port: 7990
confluence_web_context: '/confluence'

confluence_database_username: confluence
confluence_database_password: supersecure

confluence_database_host: localhost
confluence_database_port: "5432"
confluence_database_name: confluence
confluence_database_admin_username: ansible
confluence_database_admin_password: supersecure
confluence_database_template: template0

#confluence_database_jdbc_custom_config:
#  - jdbc.driver=org.postgresql.Driver
#  - jdbc...

confluence_owner: "confluence"
confluence_group: "confluence"

# Allow personal repos to be created
confluence_personal_repos: no

# TODO
#confluence_max_map_count: 262144

# Proxy and context path setup.
confluence_catalina_connector_proxyname: ~
confluence_catalina_connector_proxyport: ~
confluence_catalina_connector_scheme: "http"
confluence_catalina_connector_secure: "false"
confluence_catalina_context_path: "/"

# Atlassian Support recommended JVM arguments.
#confluence_jvm_support_recommended_args: >-
#  -Datlassian.plugins.enable.wait=300
#  -XX:+UnlockExperimentalVMOptions
#  -XX:+UseCGroupMemoryLimitForHeap
#  -XX:MaxRAMFraction=1

# Session timeout.
confluence_session_timeout: "300"

# Confluence inital setup
confluence_setup:
  display-name: Confluence
  base-url: https://sh.1.1.1.3.nip.io/confluence
  license: ''
  admin:
    username: admin
    password: supersecure
    display-name: Andy Kaufman
    mail: andy.kaufman@cicd.io

confluence_reverse_proxy:
  enable: yes
  secure: 'true'
  scheme: https
  port: 443
  hostname: sh.1.1.1.3.nip.io

#confluence_proxy:
#  host: localhost
#  port: 3128

# Facts set by lcm role - only
# confluence_database_name_version: confluence_6_7
# confluence_home_version: /opt/confluence/confluence_6_7

confluence_jmx:
  enable: yes
  remote_port: 3333
  rmi_port: 3333
  rmi_server_hostname: sh.1.1.1.11.nip.io
  password: supersecret

confluence_versions: 
  5.10.1:
    url: https://product-downloads.atlassian.com/software/stash/downloads/atlassian-confluence-5.10.1-linux-x64.bin
    checksum: sha256:d2807242530967ed4080a312128eccac2f46682ab986ceaba7fe91cf80840861
    installer_user: confluence
    # jdk:
  7.0.1:
    url: https://product-downloads.atlassian.com/software/stash/downloads/atlassian-confluence-7.0.1-x64.bin
    checksum: sha256:ad51613eee98671e0e81c41cded58af6dc69eb80bcaadbbb41e41684f3850717

confluence_versions_sequence: ['5.10.1','7.0.1']



