---
bitbucket_home: /opt/bitbucket

bitbucket_version: 5.10.1

# JVM minimal and maximum memory usage.
bitbucket_jvm_minimum_memory: "1024m"
bitbucket_jvm_maximum_memory: "1024m"

bitbucket_web_port: 7990
bitbucket_web_context: '/bitbucket'

bitbucket_database_username: bitbucket
bitbucket_database_password: supersecure

bitbucket_database_host: localhost
bitbucket_database_port: "5432"
bitbucket_database_name: bitbucket
bitbucket_database_admin_username: ansible
bitbucket_database_admin_password: supersecure
bitbucket_database_template: template0

bitbucket_owner: "bitbucket"
bitbucket_group: "bitbucket"

#bitbucket_max_map_count: 262144

# Proxy and context path setup.
bitbucket_catalina_connector_proxyname: ~
bitbucket_catalina_connector_proxyport: ~
bitbucket_catalina_connector_scheme: "http"
bitbucket_catalina_connector_secure: "false"
bitbucket_catalina_context_path: "/"

# Atlassian Support recommended JVM arguments.
bitbucket_jvm_support_recommended_args: >-
  -Datlassian.plugins.enable.wait=300
  -XX:+UnlockExperimentalVMOptions
  -XX:+UseCGroupMemoryLimitForHeap
  -XX:MaxRAMFraction=1

# Session timeout.
bitbucket_session_timeout: "300"

#bitbucket_proxy:
#  host: localhost
#  port: 3128

# Facts set by lcm role - only
# bitbucket_database_name_version: bitbucket_6_7
# bitbucket_home_version: /opt/bitbucket/bitbucket_6_7

bitbucket_versions: 
  5.10.1:
    url: https://product-downloads.atlassian.com/software/stash/downloads/atlassian-bitbucket-5.10.1-linux-x64.bin
    checksum: sha256:d2807242530967ed4080a312128eccac2f46682ab986ceaba7fe91cf80840861

bitbucket_versions_sequence: ["5.10.1"]

#bitbucket_ldap_bindpassword
#bitbucket_ldap:
#  url: ldap://localhost:389/
#  bindDn: cn=admin
#  # authentication: 
#  user: 
#    baseDn: ou=people,dc=cicd,dc=tech
#    request: uid={login}
#    realNameAttribute: cn
#    emailAttribute: mail
#  group: 
#    baseDn: ou=groups,dc=cicd,dc=tech
#    request: (&(objectClass=groupOfNames)(member={dn}))
#    idAttribute: cn
