---
lvm_roles:
  docker:
    size: '30g'
    path: '/var/lib/docker'

oracle_pluggable_databases:
  - name: JIRA
    admin: jira_dba
    password: supersecret
  - name: CONFLUENCE
    admin: confluence_dba
    password: supersecret
