---
monit_smtp:
   - host: mailrelay
     address: localhost
     port: 25
     expect_port: "^250.*"
     expect_helo: "^220.*"

proxy_skip: true

nfs_exports:
  - '/nfs/backup *(rw,sync,no_root_squash)'
  - '/nfs/backup/tmp/oracle oracle(rw,sync,no_root_squash)'
