---
- name: Generate broadcast websocket secret
  set_fact:
    broadcast_websocket_secret: "{{ lookup('password', '/dev/null', length=128) }}"
  run_once: true
  no_log: true

- import_tasks: upgrade_postgres.yml
  when:
    - postgres_data_dir is defined
    - pg_hostname is not defined

-  pip:
    name: docker-compose
    version: 1.9.0
    state: present
    extra_args: --upgrade pip

- import_tasks: set_image.yml
- import_tasks: compose.yml
