---
postgresql_version: 9.6

postgresql_pg_hba_conf:
  - host all all 1.1.1.0/24 md5

postgresql_conf:
  - listen_addresses: "'*'"

c2_alias:
  roles:
    postgresql:
      logs: ["/var/log/postgresql/*.log"]
      configs: 
        - "/var/lib/pgsql/{{ postgresql_version }}/data/pg_hba.conf"
        - "/var/lib/pgsql/{{ postgresql_version }}/data/postgresql.conf" 
