---
- name: "Upgrade all packages"
  yum:
    name: '*'
    state: latest    

- name: "Install base packages"
  become: true
  become_user: root
  tags:
    - pkg_install
  yum:
    name: "{{ item }}"
    state: present
  when: ansible_pkg_mgr == 'yum'
  with_items: "{{ packages }}"
  
