---
- name: jira-application.properties
  template:
    dest: "{{ jira_home_version_app }}/atlassian-jira/WEB-INF/classes/jira-application.properties"
    owner: "{{ jira_owner }}"
    group: "{{ jira_group }}"
    src: jira-application.properties.j2
  notify: jira-systemctl-restart

- name: Check jira properties dbconfig.xml exists at jira.home
  stat:
    path: "{{ jira_home_version_home }}/dbconfig.xml"
  register: dbconfig_xml

- name: Jira setup check
  debug:
    msg: "Jira has not been setup yet. Use a browser to navigate to http://localhost:{{ jira_web_port }}  and complete setup"
  changed_when: true
  when: not dbconfig_xml.stat.exists

- name: dbconfig.xml at jira-home
  template:
    dest: "{{ jira_home_version_home }}/dbconfig.xml"
    owner: "{{ jira_owner }}"
    group: "{{ jira_group }}"
    src: dbconfig.xml.j2
  notify: jira-systemctl-restart
  when: dbconfig_xml.stat.exists 

# - name: jira.properties
#  template:
#    dest: "{{ jira_home_version_home }}/shared/jira.properties"
#    owner: "{{ jira_owner }}"
#    group: "{{ jira_group }}"
#    src: jira.properties.j2
 # notify: jira-systemctl-restart

# - name: env file JIRA_HOME etc
#  copy:
#    content: >
#      export JIRA_HOME={{ jira_home_version_home }}
#      export JIRA_USER={{ jira_owner }}
#    dest: /etc/profile.d/jira.sh
#    owner: "{{ jira_owner }}"
#    group: "{{ jira_group }}"
