---
- name: Backup roles for node
  set_fact: backup_roles_node="{{ backup_roles_supported | intersect(ansible_role_names_cleaned) }}"

- name: Check backup installed
  stat: 
    path: "/opt/backup/bin"
  register: backup_bin

- include_tasks: "setup-{{ ansible_os_family }}.yml"

- name: Create backup dirs
  file:
    path: "{{ item }}"
    state: directory
    mode: 0700
  with_items: 
    - /etc/backup
    - /etc/backup/models
    - /etc/backup/scripts

- name: Generate example config file
  command: /opt/backup/bin/backup generate:config --config-file=/etc/backup/config-example.rb
  args:
    creates: /etc/backup/config-example.rb

- name: Config rb
  template:
    src: config.rb.j2
    dest: /etc/backup/config.rb

- name: Scripts
  template:
   dest: '/etc/backup/scripts/{{ item }}.sh'
   src: '{{ item }}.sh.j2'
  with_items: 
    - helpers
    - hooks 

- include_tasks: "models.yml"

- include_tasks: "alias.yml"
