---
- name: Restore facts
  restore_info:
    backup_archives: '{{ backup_archives }}'
    role: '{{ item }}'
    path_pattern: '{{ backup_restore[item]["path_pattern"] }}'
    force: '{{ backup_restore[item]["force"] }}'
    database: "{{ vars[item+'_database_name'] is defined }}"
    home: "{{ vars[item + '_home'] }}"    
    home_version: "{{ vars[item+'_home_version'] if vars[item+'_home_version'] is defined  }}"    
    tmp: "{{ backup_tmp }}/{{ inventory_hostname }}-{{ item }}"
    folder: '{{ backup_restore[item]["folder"] }}'   
  with_items: '{{ backup_restore }}'
  # TODO conditional vars not supported 
  # all if is defined, do not work
  
- name: backup_restore
  debug:
    var: backup_restore

- name: Tmp restore folders
  file:
    path: "{{ backup_restore[item]['tmp'] }}"
    state: directory
    mode: 0700
  when: backup_restore[item]['tar'] is defined
  with_items: '{{ backup_restore }}'

- name: Tmp restore home folders
  file:
    path: "{{  backup_restore[item]['tmp'] }}/home"
    state: directory
    mode: 0700
  when: backup_restore[item]['home_tar'] is defined    
  with_items: '{{ backup_restore }}'

- name: Extract tar
  unarchive:
    src: "{{ backup_restore[item]['tar'] }}"
    remote_src: yes
    dest: "{{ backup_restore[item]['tmp'] }}"
  when: backup_restore[item]['tar'] is defined    
  with_items: '{{ backup_restore }}'

- include_tasks: "restore_db.yml"
  when: backup_restore_db == True

- include_tasks: "restore_files.yml"
  when: backup_restore_home == True

- name: Mark restore performed
  lineinfile:
    dest: "{{ backup_restore[item]['restored-file'] }}"
    line: "{{ backup_restore[item]['sha256sum'] }}"
  when: backup_restore[item]['tar'] is defined
  with_items: '{{ backup_restore }}'

- name: Delete tmp restore folders
  file:
    path: "{{ backup_restore[item]['tmp'] }}"
    state: absent
  when: backup_restore[item]['tar'] is defined
  with_items: '{{ backup_restore }}'

#- name: Restore files
 # synchronize:
 #   src: "{{ backup_restore[item]['rsync-src'] }}"
 #   dest: "{{ backup_restore[item]['rsync-target'] }}"
 #   delete: yes
 #   recursive: yes
 # delegate_to: delegate.host    
 # when: backup_restore[item]['home_tar'] is defined    
 # with_items: '{{ backup_restore }}'


  # Ansible only allows 1 defined condition and 
  # it shoud be at the end of a multi-line condition
#
#- name: restored
#  debug:
##    var: restored
#  when: restored is defined
  

#  backup_tmp